import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {
  BsFillMoonStarsFill,
  BsTelegram,
  BsInstagram,
  BsFacebook,
} from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { Fade, Flip, Rotate, Slide, Zoom } from "react-awesome-reveal";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "" : "dark"}>
      <Head>
        <title>Next.js Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">
            <Link href="https://t.me/murod_kuchkarov">
                <a target="_blank" className="flex items-center hover:text-teal-600">
                  {" "}
                  <BsTelegram  className=" hover:scale-110 mr-1"/><Zoom>  murod_kuchkarov</Zoom>
                </a>
              </Link>
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl hover:scale-110"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
          
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Murod Kuchkarov
            </h2>
           
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              React Devoloper
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming needs. Join me down
              below and lets get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <Slide  delay={0.3}>
              <Link href="https://t.me/murod_kuchkarov">
                <a target="_blank">
                  {" "}
                  <BsTelegram  className="hover:text-teal-600 hover:scale-110"/>
                </a>
              </Link>
              </Slide>
              <Fade delay={1}>
              <Link href={"https://www.instagram.com/murod_kuchkarov/"}>
                <a target="_blank">
                  {" "}
                  <BsInstagram  className="hover:text-teal-600 hover:scale-110"/>
                </a>
              </Link>
              </Fade>
              <Slide direction="right" delay={0.3}>
              <Link href={"https://www.facebook.com/murod.qochqarov.9"}>
                  <a target="_blank"> <BsFacebook  className="hover:scale-110 hover:text-teal-600"/></a>
                </Link>
                </Slide>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" alt="deved"  className="scale-100 hover:scale-110 transition cursor-pointer"/>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance developer, Ive
              done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including programming and
              teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
           
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
            <Rotate>
              <Image src={design} width={100} height={100} alt="design"   className="hover:scale-105 cursor-pointer"/>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Frontend UI Designs
              </h3>
              <p className="py-2">
                Creating elegant web page designs suited for your needs f
              </p>
              <h4 className="py-4 text-teal-600">UI libray I Use</h4>
              <p className="text-gray-800 py-1  hover:text-teal-600">Bootstrap</p>
              <p className="text-gray-800 py-1  hover:text-teal-600">Material UI</p>
              <p className="text-gray-800 py-1  hover:text-teal-600">Ant Design</p>
              <p className="text-gray-800 py-1  hover:text-teal-600">Tailwindcss</p>
              </Rotate>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <Rotate>
              <Image src={code} width={100} height={100} alt="design"  className="hover:scale-105 cursor-pointer" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Lets make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Language I Use</h4>
              <p className="text-gray-800 py-1  hover:text-teal-600">Reactjs</p>
              <p className="text-gray-800 py-1  hover:text-teal-600">Nextjs</p>
              <p className="text-gray-800 py-1  hover:text-teal-600">Javascript</p>
              <p className="text-gray-800 py-1  hover:text-teal-600">Node.js</p>
              </Rotate>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <Rotate>
              <Image
                src={consulting}
                width={100}
                height={100}
                alt="consulting"
                className="hover:scale-105 cursor-pointer"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Connect me</h4>
              <p className="text-gray-800 py-1 hover:text-teal-600">
                <Link href="https://t.me/murod_kuchkarov">
                  <a target="_blank">Telegram account</a>
                </Link>
              </p>
              <p className="text-gray-800 py-1  hover:text-teal-600">
                <Link href={"https://www.instagram.com/murod_kuchkarov/"}>
                  <a target="_blank">Instagram account</a>
                </Link>
              </p>
              <p className="text-gray-800 py-1  hover:text-teal-600">
                {" "}
                <Link href={"https://www.facebook.com/murod.qochqarov.9"}>
                  <a target="_blank">Facebook account</a>
                </Link>
              </p>
              </Rotate>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, Ive done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Fade>
              <Image
                className="rounded-lg object-cover hover:scale-110 cursor-pointer transition"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                alt="web1"
              />
              </Fade>
            </div>
            <div className="basis-1/3 flex-1">
            <Fade>
              <Image
                className="rounded-lg object-cover hover:scale-110 cursor-pointer transition"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                alt={"web2"}
              />
            </Fade>
            </div>
            <div className="basis-1/3 flex-1">
            <Fade>
              <Image
                className="rounded-lg object-cover hover:scale-110 cursor-pointer transition"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
                alt="web3"
              />
            </Fade>
            </div>
            <div className="basis-1/3 flex-1">
            <Fade>
              <Image
                className="rounded-lg object-cover hover:scale-110 cursor-pointer transition"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                alt="web4"
              />
             </Fade>
            </div>
            <div className="basis-1/3 flex-1">
            <Fade>
              <Image
                className="rounded-lg object-cover hover:scale-110 cursor-pointer transition"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                alt="web4"
              />
          </Fade>
            </div>
            <div className="basis-1/3 flex-1">
            <Fade>
              <Image
                className="rounded-lg object-cover hover:scale-110 cursor-pointer transition"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                alt="web6"
              />
             </Fade>
            </div>
          </div>
        </section>
       
        <section>
          <div className="py-5">
           
          </div>
        </section>
     
      </main>
      
    </div>
  );
}
